export const recipeData = {
	vegetarian: false,
	vegan: false,
	glutenFree: true,
	dairyFree: true,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	lowFodmap: false,
	weightWatcherSmartPoints: 15,
	gaps: 'no',
	preparationMinutes: -1,
	cookingMinutes: -1,
	aggregateLikes: 56,
	healthScore: 39,
	creditsText: 'afrolems.com',
	sourceName: 'afrolems.com',
	pricePerServing: 167.49,
	extendedIngredients: [
		{
			id: 1032027,
			aisle: 'Spices and Seasonings',
			image: 'seasoning.png',
			consistency: 'SOLID',
			name: 'suya spice',
			nameClean: 'seasoning mix',
			original: '1.5 Tablespoons of Suya Spice',
			originalName: 'Suya Spice',
			amount: 1.5,
			unit: 'Tablespoons',
			meta: [],
			measures: {
				us: { amount: 1.5, unitShort: 'Tbsps', unitLong: 'Tbsps' },
				metric: { amount: 1.5, unitShort: 'Tbsps', unitLong: 'Tbsps' },
			},
		},
		{
			id: 5006,
			aisle: 'Meat',
			image: 'whole-chicken.jpg',
			consistency: 'SOLID',
			name: 'chicken',
			nameClean: 'whole chicken',
			original: '1 pound Chicken',
			originalName: 'Chicken',
			amount: 1,
			unit: 'pound',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: 'lb', unitLong: 'pound' },
				metric: { amount: 217.724, unitShort: 'g', unitLong: 'grams' },
			},
		},
		{
			id: 2009,
			aisle: 'Spices and Seasonings',
			image: 'chili-powder.jpg',
			consistency: 'SOLID',
			name: 'chilli powder',
			nameClean: 'chili powder',
			original: '1 teaspoon of chilli powder',
			originalName: 'chilli powder',
			amount: 1,
			unit: 'teaspoon',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: 'tsp', unitLong: 'teaspoon' },
				metric: { amount: 1, unitShort: 'tsp', unitLong: 'teaspoon' },
			},
		},
		{
			id: 4582,
			aisle: 'Oil, Vinegar, Salad Dressing',
			image: 'vegetable-oil.jpg',
			consistency: 'LIQUID',
			name: 'cooking spoon groundnut oil',
			nameClean: 'cooking oil',
			original: '1 cooking spoon groundnut oil',
			originalName: 'cooking spoon groundnut oil',
			amount: 1,
			unit: '',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: '', unitLong: '' },
				metric: { amount: 1, unitShort: '', unitLong: '' },
			},
		},
		{
			id: 99186,
			aisle: 'Meat',
			image: 'diced-ham.jpg',
			consistency: 'SOLID',
			name: 'seasoning cubes',
			nameClean: 'diced ham',
			original: 'Seasoning cubes',
			originalName: 'Seasoning cubes',
			amount: 1,
			unit: 'serving',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
				metric: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
			},
		},
		{
			id: 11282,
			aisle: 'Produce',
			image: 'brown-onion.png',
			consistency: 'SOLID',
			name: 'onions and tomatoes',
			nameClean: 'onion',
			original: 'Onions and Tomatoes for Garnishing',
			originalName: 'Onions and Tomatoes for Garnishing',
			amount: 1,
			unit: 'serving',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
				metric: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
			},
		},
		{
			id: 2047,
			aisle: 'Spices and Seasonings',
			image: 'salt.jpg',
			consistency: 'SOLID',
			name: 'salt',
			nameClean: 'table salt',
			original: 'Salt to taste',
			originalName: 'Salt to taste',
			amount: 1,
			unit: 'serving',
			meta: [],
			measures: {
				us: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
				metric: { amount: 1, unitShort: 'serving', unitLong: 'serving' },
			},
		},
	],
	id: 716342,
	title: 'Chicken Suya',
	readyInMinutes: 45,
	servings: 1,
	sourceUrl: 'http://www.afrolems.com/2014/05/27/chicken-suya/',
	image: 'https://spoonacular.com/recipeImages/716342-556x370.jpg',
	imageType: 'jpg',
	taste: {
		sweetness: 12.35,
		saltiness: 100,
		sourness: 13.36,
		bitterness: 16.52,
		savoriness: 70.03,
		fattiness: 57.4,
		spiciness: 0,
	},
	summary: `The recipe Chicken Suya can be made <b>in roughly 45 minutes</b>. This recipe serves 1 and costs $1.67 per serving. One serving contains <b>564 calories</b>, <b>44g of protein</b>, and <b>35g of fat</b>. This recipe from Afrolems requires suya spice, chicken, chilli powder, and seasoning cubes. It works well as a main course. 56 people have made this recipe and would make it again. It is a good option if you're following a <b>gluten free, dairy free, whole 30, and ketogenic</b> diet. Overall, this recipe earns a <b>solid spoonacular score of 79%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/suya-nigerian-chicken-skewers-113497">Suya (Nigerian Chicken Skewers)</a>, <a href="https://spoonacular.com/recipes/suya-swordfish-6571">Suya Swordfish</a>, and <a href="https://spoonacular.com/recipes/i-aint-chicken-chicken-crispy-roasted-chicken-breasts-with-orange-and-cardamom-1224321">I Ain't Chicken Chicken: Crispy Roasted Chicken Breasts with Orange and Cardamom</a>.`,
	cuisines: [],
	dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
	diets: ['gluten free', 'dairy free', 'whole 30', 'ketogenic'],
	instructions:
		'Heat the oven to 500 F.Wash and season the chicken with the Suya spice, chilli powder, seasoning cubes, salt and drizzle the oil over it.Place the chicken in the oven and grill for 40 minutes. Check the chicken occasionally and flip on both sides so it can cook properly.Serve hot garnished with the onions and tomato and a bit of suya spice sprinkled over the chicken.',
	analyzedInstructions: [{ name: '', steps: [Array] }],
	originalId: null,
	spoonacularScore: 93.86582946777344,
	spoonacularSourceUrl: 'https://spoonacular.com/chicken-suya-716342',
};
