import type { NextPage } from 'next';
import Head from 'next/head';
import HomePage from '../src/components/HomePage';

const Home: NextPage = () => {
	return (
		<div className='max-w-7xl mx-auto mt-2 p-6'>
			<Head>
				<title>Recipe Search App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<HomePage />
		</div>
	);
};

export default Home;
