import Head from 'next/head';
import { RecipeDetailedInfo } from '../../../src/shared/types/RecipeDetailedInfo';
import { GetServerSidePropsContext } from 'next';
import { baseUrl } from '../../../src/common/utility';
import { ApiRoutes } from '../../../src/shared/Enums/ApiRoutes';
import RecipePage from '../../../src/components/RecipePage';
import Breadcrumbs from '../../../src/shared/components/Breadcrumbs';

interface Props {
	recipeData: RecipeDetailedInfo;
}

const Recipe = ({ recipeData }: Props) => {
	return (
		<div className='max-w-7xl mx-auto mt-2 p-6'>
			<Head>
				<title>{recipeData.title}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Breadcrumbs />
			<RecipePage recipeData={recipeData} />
		</div>
	);
};

export default Recipe;

export async function getServerSideProps(context: GetServerSidePropsContext) {
	const { params } = context;
	if (!params) {
		return {
			props: {
				error: 'No recipe id provided',
				recipeData: [],
			},
		};
	}

	const { recipeSlug } = params;
	const recipeId = recipeSlug?.toString().split('-')[0];
	const response = await fetch(`${baseUrl()}${ApiRoutes.GET_RECIPE_BY_ID}?id=${recipeId}`);

	if (!response.ok) {
		console.error(`Error: ${response.status} - ${response.statusText}`);
		return {
			props: {
				error: `Error: ${response.status} - ${response.statusText}`,
				recipeData: [],
			},
		};
	}

	const recipeData: any = await response.json();

	return {
		props: {
			recipeData: recipeData,
		},
	};
}
